services:
  - type: web
    name: socialdl-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8000
      - key: ALLOWED_ORIGINS
        value: "*"
